export const FilterOptions = [
  {
    name: "Age Group",
    options: [
      "Teacher CPD",
      "11+",
      "Primary",
      "BTEC",
      "KS3",
      "KS4",
      "KS5",
      "KS2",
      "GCSE",
      "AS-level",
      "A-level",
    ],
  },
  {
    name: "Subject",
    options: [
      "Spanish",
      "Sociology",
      "Science",
      "Religous Studies",
      "Psychology",
      "Politics",
      "Biology",
      "Chemistry",
      "Physics",
      "English Literature",
      "Music",
      "History",
      "Maths",
      "Economics",
    ],
  },
  {
    name: "Exam Board",
    options: ["AQA", "Edexcel", "OCR"],
  },
  {
    name: "Skill",
    options: [
      "Verbal Reasoning",
      "Numerical Reasoning",
      "Graph Analysis",
      "Pattern Recognition",
      "Logical Reasoning",
      "Critical Thinking",
      "Deductive Reasoning",
      "Statistical Analysis",
      "Evaluation of Text",
      "Interpret sources",
      "Manipulate Fractions",
      "Describe Tabulated Data",
      "Substitute Values",
      "Deduce conclusions from graphical data",
      "Rearranging Equations",
    ],
  },
  // {
  //   name: "Tier",
  //   options: ["Higher", "Foundation"],
  // },
];
